# Site settings
title: Artful Practicality
email: chills@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing my thoughts about software with anyone unfortunate enough to read them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chills42.github.io" # the base hostname & protocol for your site
twitter_username: chills42
github_username:  chills42
timezone: US/East-Indiana

# Build settings
markdown: kramdown
